name: Build

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"

jobs:
  build-and-push:
    name: "Build go ${{ matrix.go-version }} for ${{ matrix.os }}/${{ matrix.arch }}"
    runs-on: ubuntu-24.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - "1.24"
        os:
          - darwin
          - linux
        arch:
          - amd64
          - arm64

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v1

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build binary
        shell: bash
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        # @todo: Add version to binary
        run: |
          mkdir -p dist
          go build -o dist/tinnie

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          name: tinnie-${{ matrix.os }}-${{ matrix.arch }}
          path: "dist/tinnie"
