name: Build

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"

jobs:
  build-and-push:
    name: "Build with go ${{ matrix.go-version }} on ${{ matrix.runner }}"
    runs-on: ${{ matrix.runner }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - "1.24"
        runner:
          - "ubuntu-24.04"
          - "macos-15"
          - "ubuntu-24.04-arm"
          - "macos-15-intel"

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v1

      - name: Get OS name
        id: os
        run: |
          echo "name=$(uname -s | tr '[A-Z]' '[a-z]')" >> $GITHUB_OUTPUT
          echo "arch=$(uname -m | sed 's/aarch64/arm64/' | sed 's/x86_64/amd64/')" >> $GITHUB_OUTPUT

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build binary
        shell: bash
        # @todo: Add version to binary
        run: |
          mkdir -p dist
          go build -o dist/tinnie
          ls -la dist/*
      -
        name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          name: tinnie-${{ steps.os.outputs.name }}-${{ steps.os.outputs.arch }}
          path: "dist/tinnie"
      - name: Setup Bats and Bats libs
        id: setup-bats
        uses: bats-core/bats-action@3.0.1

      - name: Test Tinnie
        shell: bash
        # env:
        #   BATS_LIB_PATH: ${{ steps.setup-bats.outputs.lib-path }}
        #   TERM: xterm
        run: bats tests/test.bats
