name: Build

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"

jobs:
  build-and-push:
    name: "Build for ${{ matrix.os }}/${{ matrix.arch }}"
    runs-on: ubuntu-24.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - darwin
          - linux
        arch:
          - amd64
          - arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup tools
        uses: jdx/mise-action@v2

      - name: Build binary
        shell: bash
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: make build

      - name: Generate checksums
        uses: Solratic/checksum-action@v1
        with:
          pattern: "dist/shippy"
          suffix: "checksum"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          name: shippy-${{ matrix.os }}-${{ matrix.arch }}
          path: "dist/shippy"

      - name: Upload a SHA Artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          name: shippy-${{ matrix.os }}-${{ matrix.arch }}-checksum
          path: "dist/shippy.checksum"
