name: Test

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

permissions:
  actions: read
  contents: read

jobs:
  test-tinnie:
    name: "Test on Linux amd64"
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v1

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          # we let the report trigger content trigger a failure using the GitHub Security features.
          args: '-no-fail -fmt sarif -out results.sarif ./...'
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v4
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          args: "--ignore-platform-reqs --optimize-autoloader"
          working_dir: "tests/typo3"

      - name: Download Linux amd64 artifact
        uses: actions/download-artifact@v4
        with:
          name: tinnie-linux-amd64
          path: dist
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Make binary executable
        shell: bash
        run: chmod +x dist/tinnie

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Setup Bats and Bats libs
        id: setup-bats
        uses: bats-core/bats-action@3.0.1

      - name: Run Tests (Serial Execution)
        shell: bash
        run: make test
